export const QUESTS = {
  'quest-1': {
    title: 'Misión 1: El misterio del nombre racista',
    subTitle: '¿Por qué una región entera lleva el nombre de una enfermedad?',
    readTimeMinutes: 3,
    body: '## Los primeros exploradores en el Catatumbo\n\nEn el siglo XVI, los **conquistadores españoles** llegaron al río Catatumbo con un objetivo claro: oro, tierras y dominio sobre los pueblos que encontraran a su paso. Explorando la **cordillera oriental**, hallaron varios asentamientos indígenas y tomaron una decisión que marcaría la historia de la región para siempre: llamarlos a todos con un único nombre colectivo.\n\n## El primer documento oficial\n\nEn **1578**, el cabildo de Ocaña —el gobierno local español de la época— elaboró el primer informe oficial sobre estos pueblos indígenas y lo envió al gobernador de Santa Marta. Ese documento describía asentamientos en la ribera del río Catatumbo, en un territorio que abarcaba desde **Abrego** hasta Ocaña, pasando por lugares como **Otare**, **Brotaré** y **Teorama**. A toda esa región la llamaron: *Provincia de los Carates*.\n\n## El error médico que lo cambió todo\n\nPero ¿qué significa "Carates"? Al observar a los indígenas, los españoles notaron que muchos tenían **manchas en la piel** de diferentes colores: blancuzcas, rojizas y de tono azul oscuro. Con su limitado conocimiento médico, concluyeron que estaban enfermos de **sarna**, una enfermedad muy temida en Europa.\n\nEl diagnóstico era completamente **equivocado**. Lo que realmente tenían era una enfermedad tropical llamada **Pinta** (también conocida como *carate* o *mal del pinto*), causada por la bacteria *Treponema carateum*. Esta infección afecta la piel, pero **no es mortal ni contagiosa** como la sarna.\n\n## Un nombre despectivo que duró siglos\n\nEn el español de los siglos XVI y XVII, "carate" se usaba para referirse a enfermedades de la piel con manchas. Los conquistadores, al ver esas marcas, empezaron a llamar a estos pueblos **"los Carates"**, es decir, "los sarnosos". Era un nombre despectivo basado en un **diagnóstico médico erróneo**, impuesto por forasteros que llegaron a un territorio ajeno y juzgaron lo que no entendían.\n\nEse nombre apareció en **mapas oficiales, documentos legales y registros históricos durante más de 200 años**.',
    speech:
      'Los primeros exploradores en el Catatumbo\n\nEn el siglo XVI, los conquistadores españoles llegaron al río Catatumbo con un objetivo claro: oro, tierras y dominio sobre los pueblos que encontraran a su paso. Explorando la cordillera oriental, hallaron varios asentamientos indígenas y tomaron una decisión que marcaría la historia de la región para siempre: llamarlos a todos con un único nombre colectivo.\n\nEl primer documento oficial\n\nEn 1578, el cabildo de Ocaña elaboró el primer informe oficial sobre estos pueblos indígenas y lo envió al gobernador de Santa Marta. Ese documento describía asentamientos en la ribera del río Catatumbo, en un territorio que abarcaba desde Abrego hasta Ocaña, pasando por lugares como Otare, Brotaré y Teorama. A toda esa región la llamaron: Provincia de los Carates.\n\nEl error médico que lo cambió todo\n\nPero ¿qué significa "Carates"? Al observar a los indígenas, los españoles notaron que muchos tenían manchas en la piel de diferentes colores: blancuzcas, rojizas y de tono azul oscuro. Con su limitado conocimiento médico, concluyeron que estaban enfermos de sarna, una enfermedad muy temida en Europa.\n\nEl diagnóstico era completamente equivocado. Lo que realmente tenían era una enfermedad tropical llamada Pinta (también conocida como carate o mal del pinto), causada por la bacteria Treponema carateum. Esta infección afecta la piel, pero no es mortal ni contagiosa como la sarna.\n\nUn nombre despectivo que duró siglos\n\nEn el español de los siglos XVI y XVII, "carate" se usaba para referirse a enfermedades de la piel con manchas. Los conquistadores, al ver esas marcas, empezaron a llamar a estos pueblos "los Carates", es decir, "los sarnosos". Era un nombre despectivo basado en un diagnóstico médico erróneo, impuesto por forasteros que llegaron a un territorio ajeno y juzgaron lo que no entendían.\n\nEse nombre apareció en mapas oficiales, documentos legales y registros históricos durante más de 200 años.',
    informativeQuestion: {
      question:
        'El nombre "Carates" duró más de 200 años en documentos oficiales. ¿Qué dice eso sobre el poder que tienen los que escriben la historia para definir a otros pueblos?',
      desc: 'Piensa en quién tenía el poder de escribir en esa época y qué pasaba con las versiones de los propios indígenas sobre sí mismos.'
    }
  },
  'quest-2': {
    title: 'Misión 2: Descubre tu barrio indígena',
    subTitle: 'Un pueblo indígena duerme bajo el asfalto de Ocaña',
    readTimeMinutes: 3,
    body: '## El pueblo que vivió donde hoy caminas\n\nDebajo del asfalto, los andenes y las casas de varios barrios de Ocaña existe un secreto que pocas personas conocen: un pueblo indígena llamado **Argutacaca** vivió exactamente en ese mismo lugar hace más de cuatro siglos.\n\nDurante las mismas exploraciones en que los españoles encontraron a los Carates, descubrieron este otro asentamiento indígena, ubicado muy cerca de lo que hoy es el **centro de Ocaña**.\n\n## El nombre que los españoles deformaron\n\nEl nombre "Argutacaca" no es original. Es una **versión españolizada** que surgió de mezclar dos palabras en lengua nativa:\n\n- **ARCUTA**: el nombre que los nativos daban a una quebrada de agua cristalina que nacía de varios manantiales de las montañas. Hoy ese río existe y se llama **Río Chiquito**.\n- **SOCOTEGAGA**: el nombre con que los propios habitantes del asentamiento se identificaban como comunidad, su identidad colectiva.\n\nAl fusionar ambas palabras, los españoles borraron los nombres originales y crearon uno nuevo: *Argutacaca*.\n\n## Los barrios actuales sobre territorio Argutacaca\n\nEl antiguo territorio Argutacaca hoy está completamente urbanizado. El Río Chiquito —antes llamado Arcuta— recorre la ciudad atravesando estos barrios:\n\n- La Carbonera · Cuesta Blanca · San Antonio · El Palomar\n- Hacaritama · Betania · El Martinete · Totumalito · Caracolí\n\nEl río cruza todos estos sectores hasta unirse con el **río Tejo** en el sector del Primero de Mayo.\n\n## El río con tres nombres\n\nEl río que pasaba por el suroccidente del poblado Argutacaca ha tenido tres nombres a lo largo de la historia:\n\n| Época | Nombre |\n|---|---|\n| Antes de 1550 (época indígena) | **Ahirar / Hcari** |\n| 1550–1800 (época colonial) | **Río Grande** |\n| Siglo XIX hasta hoy | **Río Tejo** |\n\n## ¿Qué pasó con los Argutacaca?\n\nEntre 1578 y 1700 desaparecieron como grupo étnico identificable. Los historiadores plantean tres teorías:\n\n1. **Desplazamiento forzado**: los españoles los sacaron de sus tierras fértiles para establecer haciendas.\n2. **Mestizaje y asimilación**: se mezclaron con la población española y perdieron su identidad diferenciada.\n3. **Migración**: huyeron hacia zonas remotas del bajo Magdalena, la Sierra Nevada o el Catatumbo.',
    speech:
      'El pueblo que vivió donde hoy caminas\n\nDebajo del asfalto, los andenes y las casas de varios barrios de Ocaña existe un secreto que pocas personas conocen: un pueblo indígena llamado Argutacaca vivió exactamente en ese mismo lugar hace más de cuatro siglos.\n\nDurante las mismas exploraciones en que los españoles encontraron a los Carates, descubrieron este otro asentamiento indígena, ubicado muy cerca de lo que hoy es el centro de Ocaña.\n\nEl nombre que los españoles deformaron\n\nEl nombre "Argutacaca" no es original. Es una versión españolizada que surgió de mezclar dos palabras en lengua nativa: ARCUTA, el nombre de una quebrada de agua cristalina hoy conocida como Río Chiquito; y SOCOTEGAGA, el nombre con que los habitantes se identificaban como comunidad. Al fusionar ambas palabras, los españoles borraron los nombres originales.\n\nLos barrios actuales sobre territorio Argutacaca\n\nEl antiguo territorio está hoy completamente urbanizado. El Río Chiquito cruza los barrios: La Carbonera, Cuesta Blanca, San Antonio, El Palomar, Hacaritama, Betania, El Martinete, Totumalito y Caracolí, hasta unirse con el río Tejo en el sector del Primero de Mayo.\n\nEl río con tres nombres\n\nEl río que pasaba por el suroccidente del poblado ha tenido tres nombres: antes de 1550 se llamaba Ahirar o Hcari; entre 1550 y 1800 los españoles lo llamaron Río Grande; y desde el siglo XIX se llama Río Tejo.\n\n¿Qué pasó con los Argutacaca?\n\nEntre 1578 y 1700 desaparecieron como grupo étnico. Los historiadores plantean tres teorías: desplazamiento forzado, mestizaje y asimilación, o migración hacia zonas remotas.',
    informativeQuestion: {
      question:
        'Si vivieras en uno de los barrios construidos sobre el antiguo territorio Argutacaca, ¿cómo te sentirías sabiendo que un pueblo indígena habitó exactamente donde está tu casa? ¿Cambiaría algo en la forma en que ves tu barrio?',
      desc: 'No hay respuesta incorrecta. Lo importante es que pienses en la conexión entre el pasado y los lugares que hoy habitamos sin saberlo.'
    }
  },
  'quest-3': {
    title: 'La ciencia del campo: agricultura y astronomía Argutacaca',
    subTitle:
      'Sembraban con el sol, la luna y siglos de conocimiento acumulado',
    readTimeMinutes: 3,
    body: '## Los cuatro pilares de la alimentación\n\nLa dieta Argutacaca no era improvisada. Estaba construida sobre **cuatro cultivos principales** que se complementaban entre sí para garantizar una alimentación completa y equilibrada:\n\n- 🌽 **Maíz**: el más importante. Lo transformaban en mazamorra, arepas, chicha y envueltos.\n- 🌿 **Yuca**: segunda fuente de carbohidratos. La consumían cocida, asada o como *casabe* (pan de yuca).\n- 🎃 **Ahuyama (calabaza)**: aportaba vitaminas. Se preparaba en sopas, asada, o sus semillas se tostaban.\n- 🫘 **Fríjoles**: principal proteína vegetal. En sopas, mezclados con maíz, o secos para épocas de escasez.\n\n## El calendario astronómico de siembra\n\nLos Argutacaca no sembraban al azar. Observaban el **movimiento del sol y las fases de la luna** con precisión. Conocían los **solsticios** (días más largos y más cortos del año) y tenían una regla clara sobre la luna:\n\n> 🌒 **Luna creciente** → siembra cultivos que crecen hacia arriba (maíz, fríjol)  \n> 🌘 **Luna menguante** → siembra cultivos que crecen bajo tierra (yuca)\n\nEste conocimiento no era superstición: era **ciencia práctica** acumulada durante generaciones.\n\n## Frutas casi olvidadas\n\nAdemás de los cultivos principales, consumían frutas nativas que hoy casi no se conocen en la región:\n\n- **Caimito**: morado por fuera, blanco por dentro, de sabor dulce.\n- **Chiticoma**: pequeña y dulce, parecida a una ciruela silvestre.\n\nAmbas frutas todavía existen en la zona, aunque pocas personas las conocen.\n\n## Cazadores expertos\n\nLos Argutacaca combinaban la agricultura con la caza. Su menú proteico animal incluía venados, saínos (puercos monteses), pavones de monte, paujiles y hasta pumas —cazados para proteger los animales domésticos que introdujeron los españoles—. Las **plumas de guacamayas y papagayos** no eran alimento: se usaban en ceremonias y tocados rituales.',
    speech:
      'Los cuatro pilares de la alimentación\n\nLa dieta Argutacaca estaba construida sobre cuatro cultivos principales: el maíz, el más importante, transformado en mazamorra, arepas, chicha y envueltos; la yuca, segunda fuente de carbohidratos, consumida cocida, asada o como casabe; la ahuyama o calabaza, que aportaba vitaminas; y los fríjoles, principal proteína vegetal.\n\nEl calendario astronómico de siembra\n\nLos Argutacaca no sembraban al azar. Observaban el movimiento del sol y las fases de la luna. Tenían una regla clara: la luna creciente era el momento ideal para sembrar cultivos que crecen hacia arriba, como el maíz y el fríjol; la luna menguante era el momento para sembrar cultivos que crecen bajo tierra, como la yuca. Este conocimiento era ciencia práctica acumulada durante generaciones.\n\nFrutas casi olvidadas\n\nAdemás consumían frutas nativas hoy poco conocidas: el caimito, morado por fuera y blanco por dentro, y la chiticoma, pequeña y dulce como una ciruela silvestre. Ambas todavía existen en la región.\n\nCazadores expertos\n\nCombinaban la agricultura con la caza. Cazaban venados, saínos, pavones de monte, paujiles y pumas. Las plumas de guacamayas y papagayos se usaban en ceremonias y tocados rituales.',
    informativeQuestion: {
      question:
        'Los Argutacaca sembraban según las fases de la luna y los movimientos del sol, un conocimiento acumulado durante siglos. ¿Crees que ese tipo de saber merece llamarse "ciencia"? ¿Por qué muchas veces no se le da ese reconocimiento?',
      desc: 'Piensa en la diferencia entre conocimiento escrito en libros y conocimiento transmitido de generación en generación a través de la práctica.'
    }
  },
  'quest-4': {
    title: 'Artesanos del río: pesca, arcos, barro y tejidos',
    subTitle:
      'De la arcilla al tejido: la producción material de los Argutacaca',
    readTimeMinutes: 3,
    body: '## Las herramientas de pesca y caza\n\nLos ríos **Arcuta** y **Ahirar** estaban llenos de peces en la época precolombina. Para pescarlos usaban:\n- Anzuelos de hueso\n- Redes tejidas con fibras vegetales\n- Trampas de bambú\n- Lanzas con puntas afiladas\n\nPara la caza, su herramienta más sofisticada era el **arco de madera qricua**: una madera local extremadamente flexible, resistente y liviana, de aproximadamente 1.5 metros, capaz de lanzar flechas a más de **50 metros de distancia**. Las flechas tenían punta de hueso o piedra tallada y plumas de guacamaya para estabilizar el vuelo. El color de las plumas permitía identificar a qué cazador pertenecía cada flecha.\n\n## Los tambores: más que música\n\nFabricados con **madera de qricua y piel de venado**, los tambores cumplían funciones vitales más allá de lo musical:\n- Comunicarse a distancia durante la caza\n- Coordinar ataques en batallas\n- Advertir de peligros\n- Acompañar ceremonias rituales\n\n## El arte del barro: alfarería\n\nSus creaciones en arcilla incluían ollas para cocinar, tinajas para agua, platos, vasijas para semillas y figuras ceremoniales. El proceso completo era:\n\n1. Recolección de arcilla en el lecho del río\n2. Purificación (eliminar piedras e impurezas)\n3. Amasado con agua\n4. Modelado con las manos\n5. Decoración con palitos o conchas\n6. Secado al sol (varios días)\n7. Cocción en horno de barro a alta temperatura\n8. Pintado con pigmentos naturales\n\n## Tejidos y vestuario\n\nAntes de los españoles, tejían con **algodón silvestre, fibras de palma y fique**. Después de la conquista incorporaron la **lana de oveja**. Una manta pequeña podía tomar semanas en un telar rudimentario.\n\n- 👔 **Hombres**: taparrabos de algodón, una tela de ~30 cm × 1 metro.\n- 👗 **Mujeres**: el *sayo*, una túnica rectangular doblada con abertura para la cabeza, abierta a los lados y amarrada con cordel en la cintura.\n\n## El comercio con otros pueblos\n\nLos Argutacaca **comerciaban activamente** con otros asentamientos. Ofrecían maíz, yuca seca, cerámica, tejidos, pieles de venado, plumas de guacamaya y carne ahumada. A cambio recibían principalmente **sal** (que no se producía en Ocaña), herramientas de piedra de mejor calidad y nuevos conocimientos.',
    speech:
      'Las herramientas de pesca y caza\n\nLos ríos Arcuta y Ahirar estaban llenos de peces. Para pescar usaban anzuelos de hueso, redes de fibras vegetales, trampas de bambú y lanzas. Para cazar, su herramienta más sofisticada era el arco de madera qricua: flexible, resistente y liviana, de 1.5 metros, que lanzaba flechas a más de 50 metros. Las plumas de colores en las flechas identificaban a cada cazador.\n\nLos tambores: más que música\n\nFabricados con madera qricua y piel de venado, los tambores servían para comunicarse durante la caza, coordinar batallas, advertir peligros y acompañar ceremonias rituales.\n\nEl arte del barro: alfarería\n\nCreaban ollas, tinajas, platos, vasijas y figuras ceremoniales. El proceso iba desde la recolección de arcilla en el río hasta la cocción en horno y el pintado con pigmentos naturales.\n\nTejidos y vestuario\n\nAntes de los españoles tejían con algodón silvestre, palma y fique. Después incorporaron lana de oveja. Los hombres usaban taparrabos de algodón. Las mujeres usaban el sayo, una túnica rectangular amarrada en la cintura.\n\nEl comercio con otros pueblos\n\nComercializaban maíz, cerámica, tejidos, pieles y carne ahumada. A cambio recibían principalmente sal, que no se producía en Ocaña, y herramientas de piedra de mejor calidad.',
    informativeQuestion: {
      question:
        'Los Argutacaca no producían la sal que necesitaban: la obtenían comerciando con otros pueblos. ¿Qué dice eso sobre la idea de que los pueblos indígenas vivían aislados y eran completamente autosuficientes?',
      desc: 'Piensa en qué productos necesitas tú hoy que no se producen en Ocaña y cómo llegan hasta tu mesa.'
    }
  },
  'quest-5': {
    title: 'Una sociedad sin jefes: la organización Argutacaca',
    subTitle: '"Cada quien era señor de su casa": política sin jerarquías',
    readTimeMinutes: 3,
    body: '## Las ramadas: vivir ligero por elección\n\nCuando los españoles vieron las viviendas Argutacaca, las describieron como "ranchos improvisados" y "ramadas muy miserables". Estaban equivocados. Vivían así **por elección**, no por pobreza.\n\nUna **ramada** era una estructura temporal con palos clavados en el suelo, techo de hojas de palma, paredes de ramas y piso de tierra apisonada. Sus ventajas eran claras:\n- Se construía en **2 o 3 días**\n- Usaba materiales locales, sin costo\n- Ventilación total para el clima cálido de Ocaña\n- Fácil de abandonar sin apego material\n- Se descomponía naturalmente al ser abandonada: **cero basura permanente**\n\n## El nomadismo inteligente\n\nLos Argutacaca eran **semi-nómadas**. Se mudaban por tres razones bien pensadas:\n\n1. **Rotación de suelos**: cultivaban 2–3 años en un lugar y se mudaban para que la tierra se recuperara naturalmente. Era ciencia agrícola avanzada.\n2. **Seguimiento de recursos**: se desplazaban según el agua, la caza, las frutas y la pesca de temporada.\n3. **Prevención de enfermedades**: mudarse evitaba acumulación de desechos, contaminación del agua y plagas de insectos.\n\n## La visión ecológica que los españoles destruyeron\n\nLos Argutacaca entendían algo que los conquistadores ignoraron:\n- Suelo explotado continuamente → se vuelve estéril\n- Suelo rotado → se regenera\n- Construcción con materiales naturales → cero basura permanente\n\nLos españoles hicieron lo contrario: impusieron propiedad fija, explotaron el mismo suelo sin descanso y deforestaron para haciendas. Los documentos históricos señalan que esto **influyó directamente en la desertización del paisaje ocañero**, tal como se aprecia hoy.\n\n## Sin cacique: una democracia familiar\n\nEl principio fundamental era: **"Cada quien era señor de su casa"**.\n\n- Cada familia tomaba sus propias decisiones\n- Nadie era considerado superior a otro\n- Las decisiones colectivas se tomaban por **consenso**\n- Nadie podía obligar a otro a actuar en contra de su voluntad\n\nLos españoles, acostumbrados a reyes, nobles, iglesia y alcaldes, interpretaron esto como primitivismo. En realidad era un **modelo de autonomía familiar** perfectamente adaptado a una comunidad pequeña donde todos se conocían.\n\nSe estima que la población total de la región era de **menos de 2.000 personas**.',
    speech:
      'Las ramadas: vivir ligero por elección\n\nCuando los españoles vieron las viviendas Argutacaca, las llamaron miserables. Estaban equivocados. Vivían así por elección. Una ramada se construía en 2 o 3 días con materiales locales, tenía ventilación total, era fácil de abandonar y se descomponía naturalmente: cero basura permanente.\n\nEl nomadismo inteligente\n\nEran semi-nómadas por tres razones: rotación de suelos para que la tierra se recuperara, seguimiento de recursos según la temporada, y prevención de enfermedades al evitar la acumulación de desechos.\n\nLa visión ecológica que los españoles destruyeron\n\nLos Argutacaca entendían que el suelo explotado continuamente se vuelve estéril. Los españoles impusieron propiedad fija y explotaron el mismo suelo sin descanso. Los documentos señalan que esto influyó en la desertización del paisaje ocañero.\n\nSin cacique: una democracia familiar\n\nEl principio fundamental era: "Cada quien era señor de su casa". Cada familia tomaba sus propias decisiones, nadie era superior a otro y las decisiones colectivas se tomaban por consenso. La población total era de menos de 2.000 personas.',
    informativeQuestion: {
      question:
        'Los españoles llamaron "primitivos" a los Argutacaca porque no tenían caciques ni líderes. Pero los Argutacaca tampoco tenían guerras con otros pueblos. ¿Qué dice eso sobre qué significa realmente ser una sociedad avanzada?',
      desc: 'Reflexiona: ¿una sociedad es más avanzada por tener más jerarquías y gobiernos, o por resolver sus conflictos de otra manera? No hay una sola respuesta válida.'
    }
  },
  'quest-6': {
    title: 'Rituales, lenguas y pueblos vecinos',
    subTitle:
      'Los muertos no desaparecen: creencias y conexiones de los Argutacaca',
    readTimeMinutes: 3,
    body: '## Rituales que escandalizaron a los españoles\n\nLos rituales Argutacaca eran profundamente diferentes a lo que los conquistadores conocían. Existían dos ceremonias principales:\n\n**Ritual 1 – La fiesta en honor a los caídos** \nDespués de los combates internos, realizaban una celebración con chicha, música de tambores y flautas, danzas, narrativas sobre las hazañas del muerto y lamentos cantados por las mujeres. El propósito era honrar al guerrero caído, asegurar que su espíritu descansara y despedir su alma hacia el más allá.\n\n**Ritual 2 – La danza con los ancestros** \nEl más chocante para los españoles: desenterraban muertos de 5, 10 o 20 años atrás, limpiaban sus huesos y **bailaban con los esqueletos**. Los Argutacaca creían que:\n- Los muertos no desaparecen completamente\n- El esqueleto conserva parte del espíritu\n- Bailar con los huesos reconecta con los ancestros, que brindan protección y sabiduría\n\nPosterior al ritual, volvían a enterrar los huesos con ofrendas.\n\n## Las dos lenguas de la región\n\n| Lengua | Hablada por | Estado actual |\n|---|---|---|\n| **Carate** | Pueblos cercanos al río Catatumbo, incluidos los Argutacaca | Completamente perdida |\n| **Palenque** | Nombrada por la cerca defensiva (palos con puntas) de las ramadas | Perdida |\n\nLas dos lenguas eran tan diferentes entre sí que requerían **intérpretes** para comunicarse entre comunidades.\n\n## El origen del nombre Cucuriama\n\nLos nombres de los pueblos y lenguas reflejaban el medio ambiente local. La palabra **CUCURIAMA** viene del vocablo nativo *gucua*, un tipo de palo usado para fabricar tambores. El nombre del lugar derivó directamente del material con que hacían su instrumento más importante.\n\n## Los pueblos vecinos: los Mosquito\n\nLos Argutacaca tenían contacto con los **Mosquito**, cultura del bajo Magdalena, asentados en zonas cercanas a Ocaña, en lugares hoy conocidos como **Pueblo Nuevo** y **Agua de la Virgen**. No hay registros de guerras entre ellos: probablemente mantenían **relaciones comerciales**, lo que muestra la dimensión regional de las redes indígenas de la época.\n\n## Los conflictos internos\n\nLa sociedad Argutacaca no estaba libre de violencia, aunque no peleaban contra pueblos externos. Los conflictos surgían entre ellos mismos por tres causas:\n1. **Venganzas ancestrales**: ciclos de violencia entre familias que duraban generaciones.\n2. **Consumo excesivo de chicha** en ceremonias, que hacía escalar las discusiones.\n3. **Falta de un sistema judicial** que mediara en los conflictos.',
    speech:
      'Rituales que escandalizaron a los españoles\n\nExistían dos ceremonias principales. La primera era una fiesta en honor a los caídos en combate, con chicha, música, danzas y lamentos cantados. La segunda, la más chocante para los españoles, consistía en desenterrar muertos de 5, 10 o 20 años, limpiar sus huesos y bailar con ellos. Creían que el esqueleto conservaba parte del espíritu y que bailar reconectaba con los ancestros. Luego volvían a enterrar los huesos con ofrendas.\n\nLas dos lenguas de la región\n\nExistían dos lenguas: carate, hablada por los pueblos cercanos al río Catatumbo incluidos los Argutacaca, y palenque, nombrada por las cercas defensivas de las ramadas. Ambas se perdieron completamente y eran tan diferentes que requerían intérpretes.\n\nEl origen del nombre Cucuriama\n\nLa palabra CUCURIAMA viene del vocablo nativo gucua, un tipo de palo para fabricar tambores. El nombre del lugar derivó del material con que hacían su instrumento principal.\n\nLos pueblos vecinos: los Mosquito\n\nLos Argutacaca tenían contacto con los Mosquito, cultura del bajo Magdalena, asentados en Pueblo Nuevo y Agua de la Virgen. No hay registros de guerras entre ellos.\n\nLos conflictos internos\n\nLos conflictos surgían entre los propios Argutacaca por venganzas ancestrales, consumo excesivo de chicha y falta de un sistema judicial.',
    informativeQuestion: {
      question:
        'Los Argutacaca bailaban con los huesos de sus ancestros para mantener viva la conexión con ellos. ¿Cómo crees que tu familia o comunidad mantiene viva la memoria de quienes ya no están? ¿Se parecen en algo esas formas?',
      desc: 'Piensa en los velorios, las visitas al cementerio, los altares o los rituales que conoces. No son tan diferentes en su propósito.'
    }
  }
}
